// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TopbarModuleScssNamespace {
    export interface ITopbarModuleScss {
        topbar: string;
        topbarContainer: string;
    }
}

declare const TopbarModuleScssModule: TopbarModuleScssNamespace.ITopbarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TopbarModuleScssNamespace.ITopbarModuleScss;
};

export = TopbarModuleScssModule;
